### PR TITLE
feat: Create backup script

### PR DESCRIPTION
**Pull request by DafyddLlyr**
## What does this PR do?
 - Creates a script in `package.json` to create a local backup of the Vercel db
 - Runs in docker so it's OS agnostic
 - I've added a copy of the backup to the OSL GDrive as an insurance policy, and I have one locally
 - Please try it out!

## Changes to `.env` files
 - `.env.local` is now used for the local database and Prisma client
 - `.env.production` is used for the prod database (backups)
 - Lets catch up next week to talk this through (with a diagram)

### CODE REVIEW

**Comment by zz-hh-aa** [comment]
Thanks Daf--I tried `npm run backup` but encountered this error:
```
> fairhold-dashboard@0.1.0 backup
> ./scripts/backup.sh

'.' is not recognized as an internal or external command,
operable program or batch file.
```

Not quite sure what the issue is--I tried it again, leaving out the `./` in `./scripts...` but got the same thing (`'scripts' is not recognized as an internal or external command, operable program or batch file.`

Any ideas what the issue might be?

**Comment by zz-hh-aa** [comment]
Ah-ha, Windows strikes again... do you think you could update with `cross-env` or `shx` and add to the script eg `"cross-env ./scripts/backup.sh"`? I guess we'll need this for the `test:coverage` script too.

**Comment by zz-hh-aa** [comment]
Alas no @DafyddLlyr 
``` 
Processing fstab with mount -a failed.
Failed to mount C:\, see dmesg for more details.

<3>WSL (9) ERROR: CreateProcessEntryCommon:334: getpwuid(0) failed 2
<3>WSL (9) ERROR: CreateProcessEntryCommon:505: execvpe /bin/bash failed 2
<3>WSL (9) ERROR: CreateProcessEntryCommon:508: Create process not expected to return
```

**Comment by DafyddLlyr** [comment]
Thanks for testing - I'll take a look at using a docker container for this. I think we'll need one for a local dev db anyway. PR should be open again next week!

**Comment by zz-hh-aa** [comment]
This worked for me now, but I did have to change `.env.local` to `.env`, which I guess means we'll also have to update this line in `load-env-and-prisma.js`: `require("dotenv").config({ path: ".env.local" });`

**Comment by DafyddLlyr** [comment]
Closed in favour of https://github.com/theopensystemslab/fairhold-dashboard/pull/141

**Pull request closed without merging**
